###########capcut###################################################################
tap "homebrew/bundle"
tap "homebrew/services"
tap "felixkratz/formulae"
##############################################################################
# LANGUAGES
brew "node"
brew "python@3.12"
brew "rust"
# brew "php"
# brew "go"
# brew "php"
# brew "lua"
##############################################################################
# PACKAGE MANAGER
brew "luarocks"
brew "nvm"
brew "yarn"
brew "pnpm"
brew "composer"
##############################################################################
brew "coreutils"
brew "bat" # Better cat
brew "fzf"
brew "git"
brew "neovim" # v0.11.2
brew "ripgrep"
brew "tmux"
brew "unar"
brew "eza" # Replacement for ls
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-vi-mode"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "watchman" # Watch files and take action when they change
brew "wget"
brew "starship"
brew "bash"
# Start: `brew services restart svim` and provide accessibility permissions
brew "felixkratz/formulae/svim" # Adds vim moves and modes to macOS text fields
brew "yazi"
brew "btop"
brew "fastfetch"
brew "xcodes" # To install Xcode, run: xcodes install <version> && xcodes select <version>
brew "awscli"
brew "aria2" # Download utility but faster
brew "postgresql"
brew "mysql-client@8.0"
# brew "rclone" # Rsync for cloud storage
# brew "jq"
# brew "sketchybar"
##############################################################################
cask "ghostty" # Terminal emulator
cask "google-chrome"
cask "spotify"
cask "karabiner-elements" # Keyboard remapper
cask "rectangle" # Window manager
cask "scoot" # Cursor actuator
cask "hammerspoon" # Automation tool
cask "discord"
cask "whatsapp"
cask "slack"
cask "maccy" # Clipboard manager
cask "android-studio"
cask "android-commandlinetools"
cask "blender"
cask "expo-orbit"
cask "orbstack" # Fast, ligh & simple docker/linux
cask "keycastr"
cask "obs"
cask "dbeaver-community"
cask "grammarly-desktop"
cask "free-download-manager"
cask "vlc"
cask "lulu" # Firewall
cask "zoom"
cask "android-file-transfer" # Android - macOS file transfer
cask "handbrake"
cask "logi-options+"
cask "chatgpt"
cask "capcut"
cask "postman"
cask "notion"
# cask "mos" # Mouse utility
# cask "openvpn-connect" # Work VPN
# cask "ngrok" # Prefer localtunnel (npm i -g localtunnel)
# cask "figma" # Prefer browser version
# cask "canva" # Prefer browser version
# cask "iterm2" # Prefer Ghostty
##############################################################################
# NOT ON HOMEBREW
# - Quillbot
##############################################################################
