#!/usr/bin/env bash
set -euo pipefail

[[ $(uname) == Darwin ]] || { echo 'symlink-macos.sh requires macOS' >&2; exit 1; }

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
##############################################################################
# ASCII color codes
boldGreen="\033[1;32m"
boldYellow="\033[1;33m"
# boldRed="\033[1;31m"
boldPurple="\033[1;35m"
# boldBlue="\033[1;34m"
noColor="\033[0m"
##############################################################################
mkdir -p ~/.config
mkdir -p ~/Library/LaunchAgents
mkdir -p ~/.vim/{undodir,pack,autoload,sessions}
##############################################################################
# Helper for creating symlinks
link() {
  local source_path=$1
  local target_path=$2
  local target_parent
  local backup_path
  target_parent="$(dirname "$target_path")"

  if [ -L "$target_parent" ]; then
    local linked_parent
    linked_parent="$(readlink "$target_parent")"
    linked_parent="${linked_parent%/}"
    if [[ "$source_path" == "$linked_parent/"* ]]; then
      /bin/unlink "$target_parent"
    else
      echo "Cannot replace parent symlink: $target_parent" >&2
      return 1
    fi
  fi

  mkdir -p "$target_parent"
  # Check if symlink already exists and points to the correct source
  if [ -L "$target_path" ]; then
    if [ "$(readlink "$target_path")" = "$source_path" ]; then
      # echo "$target_path exists and is correct, no action needed"
      return 0
    else
      echo -e "${boldYellow}'$target_path' is a symlink"
      echo -e "but it points to a different source, backing it up${noColor}"
    fi
  fi
  # Preserve conflicting files, directories, and symlinks.
  if [ -e "$target_path" ] || [ -L "$target_path" ]; then
    backup_path="${target_path}_backup_$(date +%Y%m%d%H%M%S)"
    while [ -e "$backup_path" ] || [ -L "$backup_path" ]; do
      backup_path="${backup_path}_next"
    done
    echo -e "${boldYellow}Backing up your existing file '$target_path' to '$backup_path'${noColor}"
    mv "$target_path" "$backup_path"
  fi
  # Create the symlink
  ln -snf "$source_path" "$target_path"
  echo -e "${boldPurple}Created or updated symlink"
  echo -e "${boldGreen}FROM: '$source_path'"
  echo -e "  TO: '$target_path'${noColor}"
}
##############################################################################
render_codex_agents() {
  local source_path="$repo_dir/codex/AGENTS.md"
  local target_path="$HOME/.codex/AGENTS.md"
  local backup_path
  local temp_path

  mkdir -p "$(dirname "$target_path")"
  temp_path="$(mktemp "${target_path}.tmp.XXXXXX")"
  sed "s|__HOME__|$HOME|g" "$source_path" > "$temp_path"
  if [ -L "$target_path" ] || { [ -e "$target_path" ] && ! grep -q '^<!-- Generated by `make agent-config`' "$target_path"; }; then
    backup_path="${target_path}_backup_$(date +%Y%m%d%H%M%S)"
    while [ -e "$backup_path" ] || [ -L "$backup_path" ]; do
      backup_path="${backup_path}_next"
    done
    mv "$target_path" "$backup_path"
  fi
  mv "$temp_path" "$target_path"
}
##############################################################################
if [ "${1:-}" = "codex" ]; then
  render_codex_agents
  exit 0
fi
##############################################################################
# Creating symlinks for files
link "$repo_dir/zsh/.zshrc" ~/.zshrc
link "$repo_dir/tmux/.tmux.conf" ~/.tmux.conf
link "$repo_dir/vim/.vimrc" ~/.vimrc
link "$repo_dir/vim/coc-settings.json" ~/.vim/coc-settings.json
link "$repo_dir/opencode/opencode.jsonc" ~/.config/opencode/opencode.jsonc
link "$repo_dir/ghui/config.json" ~/.config/ghui/config.json
link "$repo_dir/agent-of-empires/config.toml" ~/.config/agent-of-empires/config.toml
link "$repo_dir/posting/themes/rose-pine.yaml" ~/.local/share/posting/themes/rose-pine.yaml
link "$repo_dir/ghostty/config" ~/.config/ghostty/config
link "$repo_dir/starship/starship.toml" ~/.config/starship.toml
link "$repo_dir/karabiner/karabiner.json" ~/.config/karabiner/karabiner.json
link "$repo_dir/karabiner/open-android-emulator.sh" ~/.config/karabiner/open-android-emulator.sh
link "$repo_dir/yazi/yazi.toml" ~/.config/yazi/yazi.toml
link "$repo_dir/yazi/keymap.toml" ~/.config/yazi/keymap.toml
link "$repo_dir/yazi/theme.toml" ~/.config/yazi/theme.toml
link "$repo_dir/yazi/flavors/rose-pine.yazi" ~/.config/yazi/flavors/rose-pine.yazi
link "$repo_dir/eza/theme.yml" ~/.config/eza/theme.yml
link "$repo_dir/fastfetch/config.jsonc" ~/.config/fastfetch/config.jsonc
link "$repo_dir/aerospace/aerospace.toml" ~/.config/aerospace/aerospace.toml
link "$repo_dir/borders/bordersrc" ~/.config/borders/bordersrc
link "$repo_dir/lazygit/config.yml" ~/.config/lazygit/config.yml
link "$repo_dir/lazydocker/config.yml" ~/.config/lazydocker/config.yml
link "$repo_dir/git/ignore" ~/.config/git/ignore
link "$repo_dir/mise/config.toml" ~/.config/mise/config.toml
link "$repo_dir/rainfrog/rainfrog_config.toml" ~/.config/rainfrog/rainfrog_config.toml
link "$repo_dir/kact/kact.toml" ~/.config/kact/kact.toml
render_codex_agents
##############################################################################
# Creating symlinks for directories
link "$repo_dir/nvim/" ~/.config/nvim
link "$repo_dir/svim/" ~/.config/svim
link "$repo_dir/btop/" ~/.config/btop
link "$repo_dir/sketchybar/" ~/.config/sketchybar
link "$repo_dir/tuicr/" ~/.config/tuicr
link "$repo_dir/posting" ~/.config/posting
link "$repo_dir/spicetify/Themes/RosePine" ~/.config/spicetify/Themes/RosePine
##############################################################################
