# Default keymaps: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
[mgr]

prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
  { on = "~", run = "find --previous --smart", desc = "Find previous file" },
]
