require("lazy").setup({
  require("plugins.mason"),
  require("plugins.git"),
  require("plugins.which-key"),
  require("plugins.telescope"),
  require("plugins.lspconfig"),
  require("plugins.conform"),
  require("plugins.cmp"),
  require("plugins.tokyonight"),
  require("plugins.mini"),
  require("plugins.treesitter"),
  require("plugins.debug"),
  require("plugins.indent_line"),
  require("plugins.lint"),
  require("plugins.autopairs"),
  require("plugins.autotag"),
  require("plugins.rest"),
  require("plugins.markdown"),
  require("plugins.server"),
  require("plugins.oil"),
  require("plugins.dashboard"),
  require("plugins.noice"),
  require("plugins.wakatime"),
  require("plugins.tmux"),
  require("plugins.comment"),
  require("plugins.sleuth"),
  require("plugins.loft"),
  require("plugins.copilot"),
  require("plugins.tabby"),
  -- require("plugins.avante"),
  -- DEV
  -- { import = "plugins._dev.loft" },
}, {
  ui = {
    icons = vim.g.have_nerd_font and {} or {
      cmd = "⌘",
      config = "🛠",
      event = "📅",
      ft = "📂",
      init = "⚙",
      keys = "🗝",
      plugin = "🔌",
      runtime = "💻",
      require = "🌙",
      source = "📄",
      start = "🚀",
      task = "📌",
      lazy = "💤 ",
    },
    border = "rounded",
  },
})
