import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

type Action = string;
type Layer = Record<string, Action>;
const XX = 'XX';
const kanataDir = dirname(fileURLToPath(import.meta.url));

const command = (...args: string[]): Action => `(cmd-log none error ${args.map(quote).join(' ')})`;
const desktop = (pattern: string, desktopId: string): Action =>
  command(join(kanataDir, 'window'), 'desktop', pattern, desktopId);
const webapp = (pattern: string, url: string): Action =>
  command(join(kanataDir, 'window'), 'webapp', pattern, url);
const heldLayer = (name: string): Action => `(layer-while-held ${name})`;
const subLayer = (name: string): Action => `(one-shot 2000 ${heldLayer(name)})`;

const layers: Record<string, Layer> = {
  base: {
    caps: '(tap-hold-press 200 200 caps (layer-while-held hyper))',
    ___: '_',
  },
  hyper: {
    b: subLayer('browse'),
    o: subLayer('open'),
    e: subLayer('mouse'),
    w: subLayer('window'),
    s: subLayer('system'),
    v: subLayer('move'),
    c: subLayer('music'),
  },
  browse: {
    x: command('omarchy-launch-browser', 'https://x.com'),
  },
  open: {
    a: command(join(kanataDir, 'window'), 'previous-app'),
    c: desktop('google-chrome', 'google-chrome.desktop'),
    j: desktop('google-chrome', 'google-chrome.desktop'),
    g: desktop('com.mitchellh.ghostty', 'com.mitchellh.ghostty.desktop'),
    f: desktop('org.gnome.Nautilus', 'org.gnome.Nautilus.desktop'),
    s: desktop('spotify', 'spotify-launcher.desktop'),
    d: webapp('dictionary', 'https://www.google.com/search?q=define%3A'),
    n: desktop('obsidian', 'obsidian.desktop'),
    k: desktop('slack', 'slack.desktop'),
    w: desktop('whatsapp', 'WhatsApp.desktop'),
    r: desktop('discord', 'Discord.desktop'),
    p: desktop('postman', 'postman.desktop'),
    z: desktop('zoom', 'Zoom.desktop'),
    h: desktop('notion', 'Notion.desktop'),
    b: desktop('dbeaver', 'io.dbeaver.DBeaver.desktop'),
    l: desktop('blender', 'blender.desktop'),
    y: desktop('chrome-youtube.com__-Default', 'YouTube.desktop'),
    m: desktop('chrome-music.youtube.com__-Default', 'YouTube Music.desktop'),
    e: desktop('photopea', 'Photopea.desktop'),
    t: desktop('jetbrains-studio', 'android-studio.desktop'),
    x: XX,
    ',': XX,
    '.': XX,
    i: XX,
  },
  mouse: {
    f: command('kact', 'activate', 'elements'),
    '/': command('kact', 'activate', 'grid'),
    h: '(movemouse-accel-left 10 800 2 15)',
    j: '(movemouse-accel-down 10 800 2 15)',
    k: '(movemouse-accel-up 10 800 2 15)',
    l: '(movemouse-accel-right 10 800 2 15)',
    ret: 'mlft',
    spc: 'mlft',
    i: '(mwheel-up 50 120)',
    o: '(mwheel-down 50 120)',
    ',': '(mwheel-left 50 120)',
    '.': '(mwheel-right 50 120)',
    lctl: heldLayer('mouse-control'),
    lmet: heldLayer('mouse-fast'),
    ralt: heldLayer('mouse-center-click'),
    lalt: heldLayer('mouse-slow'),
  },
  'mouse-control': { h: 'left', j: 'down', k: 'up', l: 'rght', ret: 'mrgt', spc: 'mrgt' },
  'mouse-fast': {
    h: '(movemouse-accel-left 10 800 8 60)',
    j: '(movemouse-accel-down 10 800 8 60)',
    k: '(movemouse-accel-up 10 800 8 60)',
    l: '(movemouse-accel-right 10 800 8 60)',
    ret: 'mlft',
    spc: 'mlft',
  },
  'mouse-center-click': { ret: 'mmtp', spc: 'mmid' },
  'mouse-slow': {
    h: '(movemouse-accel-left 10 800 1 6)',
    j: '(movemouse-accel-down 10 800 1 6)',
    k: '(movemouse-accel-up 10 800 1 6)',
    l: '(movemouse-accel-right 10 800 1 6)',
    ret: 'mlft',
    spc: 'mlft',
  },
  window: {
    e: '(macro esc esc)',
    h: 'mbck',
    i: command(join(kanataDir, 'window'), 'shortcut', 'previous-tab'),
    o: command(join(kanataDir, 'window'), 'shortcut', 'next-tab'),
    p: command(join(kanataDir, 'window'), 'cycle', 'prev'),
    n: command(join(kanataDir, 'window'), 'cycle', 'next'),
    l: 'mfwd',
  },
  system: {
    o: command('omarchy-audio-output-volume', 'raise'),
    i: command('omarchy-audio-output-volume', 'lower'),
    k: command('omarchy-brightness-display', '+5%'),
    j: command('omarchy-brightness-display', '5%-'),
    l: command('omarchy-system-lock'),
    c: 'S-M-c',
  },
  move: { h: 'left', j: 'down', k: 'up', l: 'rght', i: 'pgdn', o: 'pgup' },
  music: {
    spc: command('playerctl', 'play-pause'),
    k: command('playerctl', 'next'),
    j: command('playerctl', 'previous'),
  },
};

const output = `;; Generated by config.ts. Run: make kanata\n\n(defcfg\n  process-unmapped-keys yes\n  danger-enable-cmd yes\n  linux-device-detect-mode keyboard-only\n)\n\n(defsrc)\n\n${Object.entries(layers)
  .map(([name, mappings]) => layer(name, mappings))
  .join('\n\n')}\n`;

writeFileSync(join(dirname(fileURLToPath(import.meta.url)), 'kanata.kbd'), output);

function layer(name: string, mappings: Layer): string {
  return `(deflayermap (${name})\n${Object.entries(mappings)
    .map(([key, action]) => `  ${key.padEnd(6)} ${action}`)
    .join('\n')}\n)`;
}

function quote(value: string): string {
  if (/^[A-Za-z0-9_./:%+@=-]+$/.test(value)) return value;
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}
