#!/usr/bin/env bash
set -euo pipefail

source_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/AGENTS.md"
target_path="$HOME/.codex/AGENTS.md"

mkdir -p "$(dirname "$target_path")"
temp_path="$(mktemp "${target_path}.tmp.XXXXXX")"
sed "s|__HOME__|$HOME|g" "$source_path" > "$temp_path"

if [ -L "$target_path" ] || { [ -e "$target_path" ] && ! grep -q '^<!-- Generated by `make agent-config`' "$target_path"; }; then
  backup_path="${target_path}_backup_$(date +%Y%m%d%H%M%S)"
  while [ -e "$backup_path" ] || [ -L "$backup_path" ]; do
    backup_path="${backup_path}_next"
  done
  mv "$target_path" "$backup_path"
fi

mv "$temp_path" "$target_path"
